name: Tests
on: [push]
  # pull_request:
  #   branches: 
  #     - master
  #   types: [opened, synchronize, reopened, ready_for_review]

jobs:
  npm-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
  failure-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "failure tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-Failure.xml"
          debug: true
      - name: Assert success
        if: failure()
        run: |
          echo "::error::failure-tests should have succeeded, and created a new check that failed with annotations. But instead failed";
          exit 1;
  failure-tests-notoken:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "failure tests no token"
          path: "**/TEST-Failure.xml"
          debug: true
      - name: Assert failure
        if: success()
        run: |
          echo "::error::failure-tests-notoken should have failed and reported annations on this step. But instead succeeded";
          exit 1;
  error-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "error tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-Error.xml"
          debug: true
      - name: Assert success
        if: failure()
        run: |
          echo "::error::error-tests should have succeeded, and created a new check that failed with annotations. But instead failed";
          exit 1;
  error-tests-notoken:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "error tests no token"
          path: "**/TEST-Error.xml"
          debug: true
      - name: Assert failure
        if: success()
        run: |
          echo "::error::error-tests-notoken should have failed and reported annations on this step. But instead succeeded.";
          exit 1;
  success-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "Success tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-Success.xml"
          debug: true
      - name: Assert success
        if: failure()
        run: |
          echo "::error::success-tests should have succeeded, and created a new check that failed with annotations. But instead failed";
          exit 1;
  success-tests-notoken:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          name: "Success tests no token"
          path: "**/TEST-Success.xml"
          debug: true